build: fix build tasks and include build and link in githooks (#11)
Co-authored-by: Daniel Wood <ddubs@amazon.com>

diff --git a/source/common/git-hooks/pre-commit b/source/common/git-hooks/pre-commit
--- a/source/common/git-hooks/pre-commit
+++ b/source/common/git-hooks/pre-commit
@@ -10,5 +10,10 @@
 cd source
 node common/scripts/install-run-rush.js git-secrets-scan || exit $?
 node common/scripts/install-run-rush.js prettier || exit $?
-# node source/common/scripts/install-run-rush.js common-coverage-make-badge || exit $?
-node common/scripts/install-run-rush.js sort-package-json && git add **/package.json || exit $?
+node common/scripts/install-run-rush.js lint:fix -o @aws/dea-app -o @aws/dea-ui -o @aws/dea-ui-infrastructure -o @aws/dea-backend || exit $?
+node common/scripts/install-run-rush.js add-license-header -o @aws/dea-app -o @aws/dea-ui -o @aws/dea-ui-infrastructure -o @aws/dea-backend || exit $?
+node common/scripts/install-run-rush.js sort-package-json -o @aws/dea-app -o @aws/dea-ui -o @aws/dea-ui-infrastructure -o @aws/dea-backend && git add **/package.json || exit $?
+if ! node common/scripts/install-run-rush.js build:test -o @aws/dea-app -o @aws/dea-ui -o @aws/dea-ui-infrastructure -o @aws/dea-backend; then
+    echo "\033[0;31mA Failure was encountered, please check the output above\033[0m"
+    exit 1
+fi
