build: require opt in for git hooks (#38)

diff --git a/source/common/git-hooks/pre-commit b/source/common/git-hooks/pre-commit
--- a/source/common/git-hooks/pre-commit
+++ b/source/common/git-hooks/pre-commit
@@ -7,13 +7,15 @@
 # are committed. The command is defined in common/config/rush/command-line.json
 # and uses the "rush-prettier" autoinstaller.
 
-cd source
-node common/scripts/install-run-rush.js git-secrets-scan || exit $?
-node common/scripts/install-run-rush.js prettier || exit $?
-node common/scripts/install-run-rush.js lint:fix || exit $?
-node common/scripts/install-run-rush.js add-license-header|| exit $?
-node common/scripts/install-run-rush.js sort-package-json && git add **/package.json || exit $?
-if ! node common/scripts/install-run-rush.js build:test; then
-    echo "\033[0;31mA Failure was encountered, please check the output above\033[0m"
-    exit 1
+if [ "$RUN_HOOKS" == true ]; then
+    cd source
+    node common/scripts/install-run-rush.js git-secrets-scan || exit $?
+    node common/scripts/install-run-rush.js prettier || exit $?
+    node common/scripts/install-run-rush.js lint:fix || exit $?
+    node common/scripts/install-run-rush.js add-license-header|| exit $?
+    node common/scripts/install-run-rush.js sort-package-json && git add **/package.json || exit $?
+    if ! node common/scripts/install-run-rush.js build:test; then
+        echo "\033[0;31mA Failure was encountered, please check the output above\033[0m"
+        exit 1
+    fi
 fi
